# Generated by Django 6.0.1 on 2026-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
