# Generated by Django 6.0.1 on 2026-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_attempt_max_score_attempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
